### ISSUE TITLE
Custom log parser improvement and fix

### ISSUE THREAD

**Issue by Tolriq** [Gegenbauer/CatSpy#30]
The custom log parser is nice but the interface is a little to rigid to support complex splits with chars that can be present in the message.

1) MergeNearbyParts requires a **To** value that is in the range of possible part count based on the single sample line. This is problematic as we may not know the actual end for some cases. It should be able to support a empty value for the To to support this need.
2) MergeUntilCharOp issues: Unlike MergeNearbyParts it does not add the " " so is hard to use as a replacement for MergeNearbyParts + if the targetChar is not found it ignore the start value due to missing `  if (!mergedComplete) {
                yield(mergedPart.toString())
            }` at the end of the sequence builder.

**Comment by Gegenbauer** [comment]
May be we can discuss about the detail of Log Customization. You can find my email in my profile.

**Comment by Tolriq** [comment]
Nothing fancy but the log files looks like:
``` 2024-09-24 02:24:02.247 Verbose/SubsonicLogger: --> [363] GET http://192.168.1.3:30043/rest/getSong.view?id=096291b3f2e932a0f7e0444b40ae1479&u=REDACTED&t=REDACTED&s=REDACTED&v=1.13.0&c=Symfonium&f=json
2024-09-24 02:24:04.583 Verbose/SubsonicLogger: <-- [719] {"subsonic-response":{"status":"ok","version":"1.16.1","type":"navidrome","serverVersion":"0.53.2 (3910e77a)","openSubsonic":true}}
``` 
So `date` space `time` space `level` slash `tag` column space `message` 

Easy to parse with MergeNearbyParts without a to field or by using a fake char in MergeUntilCharOp with the 2 small fixes suggested.

**Comment by Gegenbauer** [comment]
I will modify it at the next release.

**Comment by Tolriq** [comment]
Actually I have another small issue:

```
2024-09-25 10:23:30.314 Verbose/ExoPlayer: tracks [eventTime=791.71, mediaPos=0.00, window=0, period=0
2024-09-25 10:23:30.315 Verbose/ExoPlayer:   group [
2024-09-25 10:23:30.315 Verbose/ExoPlayer:     [X] Track:0, id=null, mimeType=audio/flac, pcmEncoding=21, channels=2, sample_rate=48000, supported=YES
2024-09-25 10:23:30.316 Verbose/ExoPlayer:   ]
2024-09-25 10:23:30.316 Verbose/ExoPlayer:   Metadata [
2024-09-25 10:23:30.316 Verbose/ExoPlayer:     VC: ARTIST=水曜日のカンパネラ
2024-09-25 10:23:30.317 Verbose/ExoPlayer:     VC: TITLE=赤猫
2024-09-25 10:23:30.317 Verbose/ExoPlayer:     VC: ALBUM=POP DELIVERY
2024-09-25 10:23:30.318 Verbose/ExoPlayer:     VC: DATE=2024.06.05
2024-09-25 10:23:30.318 Verbose/ExoPlayer:     VC: GENRE=J-Pop
2024-09-25 10:23:30.319 Verbose/ExoPlayer:     VC: COMPOSER=Kenmochi Hidefumi
2024-09-25 10:23:30.322 Verbose/ExoPlayer:     VC: ALBUMARTIST=水曜日のカンパネラ
2024-09-25 10:23:30.323 Verbose/ExoPlayer:     VC: TRACKNUMBER=1
2024-09-25 10:23:30.323 Verbose/ExoPlayer:     VC: TRACKTOTAL=8
2024-09-25 10:23:30.323 Verbose/ExoPlayer:     VC: DISCNUMBER=1
2024-09-25 10:23:30.324 Verbose/ExoPlayer:     VC: DISCTOTAL=1
2024-09-25 10:23:30.324 Verbose/ExoPlayer:     VC: COPYRIGHT=℗© 2024 WARNER MUSIC JAPAN INC.
2024-09-25 10:23:30.324 Verbose/ExoPlayer:     VC: LABEL=WM Japan
2024-09-25 10:23:30.325 Verbose/ExoPlayer:   ]
2024-09-25 10:23:30.325 Verbose/ExoPlayer: ]
```

I can't find a way to keep the spaces to ease the reading of the logs.

**Comment by Gegenbauer** [comment]
![image](https://github.com/user-attachments/assets/17fcb906-196d-409c-9573-6936ac2b3d3a)
![image](https://github.com/user-attachments/assets/76042a62-38f8-4a3d-b327-845485ef225a)


[catspy_DefaultRawLog_1.json](https://github.com/user-attachments/files/17173660/catspy_DefaultRawLog_1.json)
put log metadata json file at “Catspy Menu -> Help -> Show Log In Files” metadata folder

**Comment by Gegenbauer** [comment]
![image](https://github.com/user-attachments/assets/e12f03ce-fad1-4078-977d-1d6ad3b9c552)

**Comment by Tolriq** [comment]
This is strange I get 2 mails but can only see 1 message from you here,

The solution in the mail to remove the trim in MergeNearbyPartsOp only works if I can use MergeNearbyPartsOp but can't due to the fact that it needs a to from a single sample line and I can have lines with very large parts.

For the moment I'd like to contribute here and not fork, hence the requests.

**Comment by Gegenbauer** [comment]
It's not strange. I deleted the previous response because I found some mistakes in it. Certainly, you can contribute, and I would appreciate it if you do.

**Comment by Gegenbauer** [comment]
I also realized that the Log Parser feature is still too difficult for users to use, and perhaps only I understand how to use it. Additionally, due to the diversity of log formats, unexpected parsing results may occur because of certain special characters.

**Comment by Tolriq** [comment]
Well I think it's not that difficult, it's just opinionated.

I'm still trying to debug the code to figure out how the parsers part works.

I can't figure out how you reached that screen above

![image](https://github.com/user-attachments/assets/02f57660-b956-4fd6-975d-aa5d821b5342)

The first sub processor have already lost the spaces in each parts.

**Comment by Gegenbauer** [comment]
You can provide the sample files for the two kinds of logs which are mentioned above.

**Comment by Tolriq** [comment]
They are both of the same previously given format: `date` space `time` space `level` slash `tag` column space `message`

[debug (18).log](https://github.com/user-attachments/files/17173859/debug.18.log)

Anyway the problem is that `SplitByWordSeparatorOp` uses "\\s+" as the regex to split that looses the spaces.

So the workaround could be to reduce the max number of splits to one less.

But then we need to split the last part with `:` then join the rest (again problematic due to MergeNearby part needing a To value). And worse is that then the `:` are lost in the message.

![image](https://github.com/user-attachments/assets/884c3e2a-37d8-4f3e-96d8-3763b689f0d8)

So would require either a limit to SplitPartWithChar to only split the first one. Or a merge character parameter to MergeUntilChar or MergeNearbyParts (if no limits) to add back the split character on the rest.

**Comment by Tolriq** [comment]
Created a PR for this one to add support for maxParts to SplitPartWithChar this solve this issue with for example:

![image](https://github.com/user-attachments/assets/9a8a21aa-1473-4c82-97f5-f1acf2fdf66c)

**Comment by Tolriq** [comment]
Thanks for the merge.

**Comment by Gegenbauer** [comment]
[catspy_DefaultRawLog_1.json](https://github.com/user-attachments/files/17174939/catspy_DefaultRawLog_1.json
Try this log metadata to parse the sample log file that you provided above.
![image](https://github.com/user-attachments/assets/34dfe11c-9245-49da-bb39-2e550ac17643)

By open Catspy Menu->Show Log in Files. Put it in metadata folder and reopen Catspy.

**Comment by Tolriq** [comment]
With the PR merged the solution from https://github.com/Gegenbauer/CatSpy/issues/30#issuecomment-2380644026 does work nicely. 

But your extract shows one limitation of the tool currently with multiline logs, since they are individual lines, the stack trace does not inherit the error log level.

**Comment by Gegenbauer** [comment]
yes. maybe for log lines that are not started with time, it can inherit the time, level, tag of the last full log

**Comment by Gegenbauer** [comment]
For logcat, the stack will also contain time pid tid tag...
