### ISSUE TITLE
Default file open configuration

### ISSUE THREAD

**Issue by Tolriq** [Gegenbauer/CatSpy#35]
Opening this just for discussion.

See https://github.com/Tolriq/CatSpy/commit/8dd18e0ea76bfeac62918ae49f34823825428faf

Usually details view + sort by most recent change is the most needed default values to open logs.

Since it bothered me a lot to do tons of click I've quickly added this hack, but maybe there's something to be done here as default or setting?

**Comment by Gegenbauer** [comment]
It supports dragging file into HomePanel or FileLogPanel

**Comment by Tolriq** [comment]
I'm under Gnome wayland with half pop_os cosmic and drag and drop fails for many use cases. But I guess it can works for the others so no need to add this on your side so.I'm under Gnome wayland with half pop_os cosmic and drag and drop fails for many use cases. But I guess it can works for the others so no need to add this on your side so.
