### ISSUE TITLE
中文编码问题

### ISSUE THREAD

**Issue by FluteY2** [Gegenbauer/CatSpy#4]
中文会显示为乱码
![Snipaste_2024-06-14_15-15-21](https://github.com/Gegenbauer/CatSpy/assets/68569862/f9bf03d6-e793-415b-9594-a5c06492882b)

在android studio或者直接adb可以看到这行是：Display device changed state: "内置屏幕", OFF
其他处中文同样会显示为乱码

**Comment by Gegenbauer** [comment]
之前没时间开发，这个问题已在1.1.1 修复，有问题欢迎反馈
