### ISSUE TITLE
自定义字体和模板设置保存问题

### ISSUE THREAD

**Issue by Bamboo-D** [Gegenbauer/CatSpy#40]
在主题中修改字体并保存后，即使`settings.json`中存储了值，`catspy.log`也显示读取到了字体设置，打开CatSpy后依旧会变回默认的 双Dialog 14，设置和实际显示都是，但`settings.json`依旧是自定义的值。

新建自定义log模板无法删除，点删除后它永远在那里

以上在win11 24H2和ubuntu 2004中测试均相同。

**Comment by Gegenbauer** [comment]
感谢反馈，会尽快修复

**Comment by Gegenbauer** [comment]
Fixed at 1.1.9
